apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-reddit
  template:
    metadata:
      labels:
        app: auth-reddit
    spec:
      containers:
        - name: auth-reddit
          image: haalpme/reddit-auth
          env:
            - name: MONGO_URI
              value: 'mongodb://auth-mongo-srv:27017/auth'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv-reddit
spec:
  selector:
    app: auth-reddit
  ports:
    - name: auth-reddit
      protocol: TCP
      port: 3000
      targetPort: 3000
