apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-reddit
  template:
    metadata:
      labels:
        app: client-reddit
    spec:
      containers:
        - name: client-reddit
          image: haalpme/reddit-client
          env:
            - name: STRIPE_KEY
              valueFrom:
                secretKeyRef:
                  name: stripe-secret
                  key: STRIPE_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: client-srv-reddit
spec:
  selector:
    app: client-reddit
  ports:
    - name: client-reddit
      protocol: TCP
      port: 3000
      targetPort: 3000
