apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: post-reddit
  template:
    metadata:
      labels:
        app: post-reddit
    spec:
      containers:
        - name: post-reddit
          image: haalpme/reddit-post
          env:
            - name: MONGO_URI
              value: 'mongodb://post-mongo-srv:27017/post'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: post-srv-reddit
spec:
  selector:
    app: post-reddit
  ports:
    - name: post-reddit
      protocol: TCP
      port: 3000
      targetPort: 3000
